### ISSUE TITLE
Font resolution is low on MacOS without building (will test built version later)

### ISSUE THREAD

**Issue by MinecraftPublisher** [face-hh/griddycode#71] opened 2024-03-25 08:48 UTC
Also, Zed was not built exclusively for MacOS and they're working on a Linux and Windows release.

Plus, I could build the Mac version for you if you want

**Comment by face-hh** [comment] 2024-03-25 08:50
We won't support the fruit os as I don't want to rely on someone else to test each build

**Comment by face-hh** [comment] 2024-03-25 15:01
Duplicate of #72

**Closed** 2024-03-25 15:01 UTC
Labels: bug

**Comment by MinecraftPublisher** [comment] 2024-03-25 17:02
wait why was it posted twice damn
