### ISSUE TITLE
Cant figure out Nerdfont

### ISSUE THREAD

**Issue by LOLYAYDEV** [face-hh/griddycode#9] opened 2024-03-19 18:58 UTC
I tried installing every font on the nerdfont website but i still se the glyphs. What fonts should i doenload and where. Im using windows 11

**Comment by rottakore** [comment] 2024-03-19 19:38
I think you only need one nerdfont, the problem is that there's no way to configure the font in the app, I think it defaults to the primary font of the OS

**Comment by 7valkio** [comment] 2024-03-19 20:55
I have installed the FiraCode Nerd Font and FiraMono Nerd Font but when I open the Griddycode, it still gives blurry characters.

https://github.com/face-hh/griddycode/assets/113270877/2a906792-698f-4d7b-b805-aaaf8b929f82

**Comment by BurningButter** [comment] 2024-03-19 20:57
Try 0xProto Nerd Font, its the first one that pops up and it worked for me.

**Comment by 7valkio** [comment] 2024-03-19 21:17
I tried installing the 0xProto Nerd Font, still showing blurry on Windows 11.

**Comment by ThreeTheOG** [comment] 2024-03-19 21:58
Same here.

**Comment by face-hh** [comment] 2024-03-20 15:46
Closing as it now works on v1.0.4

**Closed by face-hh** 2024-03-20 15:46 UTC
