### ISSUE TITLE
Blinding Lights (ft. Win 11)

### ISSUE THREAD

**Issue by not-yuvi** [face-hh/griddycode#69] opened 2024-03-25 06:31 UTC
Accidentally switched to "Github Light" Theme and its way too light on Windows 11,
other themes are on par with vs code but the light theme seems too high
![image](https://github.com/face-hh/griddycode/assets/63899378/b8b9296c-18f6-4940-9f98-4a55d2ee6616)

**Comment by face-hh** [comment] 2024-03-25 06:31
Disable "glow" in the settings

**Comment by Symmettry** [comment] 2024-03-25 06:32
Looks good to me /s

**Comment by not-yuvi** [comment] 2024-03-25 06:36
> Disable "glow" in the settings

that works, but I got softlocked when it was enabled and had to rely on the yt video to guess where it was lol, there should be an indicator to prevent this from happening to other users (I recommend)

**Comment by ItsTato** [comment] 2024-03-25 06:37
glow shouldn't make light mode implode
thats bug

**Comment by not-yuvi** [comment] 2024-03-25 06:38
> glow shouldn't make light mode implode thats bug

try glow + light + CRT

**Comment by ItsTato** [comment] 2024-03-25 06:38
military administered flashbang combo

**Comment by not-yuvi** [comment] 2024-03-25 18:26
This issue is crazy 69
<img width="962" alt="image" src="https://github.com/face-hh/griddycode/assets/63899378/87a8ecb2-74f2-475e-80b8-33ccd2944f8d">

**Comment by face-hh** [comment] 2024-03-29 18:23
A `disable_glow()` function will be added for the themes Lua API to combat this - unless someone finds a way to fix this, since it's caused by the `WorldEnvironment` node, specifically the `glow` property.

**Comment by face-hh** [comment] 2024-03-30 07:35
This has been fixed in v1.2.0, via `disable_glow()`. It has been added to most light themes by me :+1:

**Closed by face-hh** 2024-03-30 07:35 UTC
Labels: bug
