### ISSUE TITLE
Broken on open

### ISSUE THREAD

**Issue by SleeplessScripter** [face-hh/griddycode#36] opened 2024-03-23 00:30 UTC
When opening GriddyCode the window does not have the minimize, window, and close buttons. Nothing loads and music does not play.

To reproduce, I guess just open the program.....

I expected for the program to open and run normally

![image](https://github.com/face-hh/griddycode/assets/104847775/4b9ce73d-8200-487c-9398-fbf7dd46d035)

OS - Windows
Version - 11 22H2

**Comment by Symmettry** [comment] 2024-03-23 02:11
The buttons were removed, it’s not a bug that they don’t exist.

You have to turn on the music in GriddyCode settings.

**Comment by face-hh** [comment] 2024-03-23 04:41
Could you run the program via the command line? I.e. "./GriddyCode.exe"

**Comment by Lucas104-alt** [comment] 2024-03-23 15:23
Me too but now is fixed

**Comment by face-hh** [comment] 2024-03-23 15:27
Closing as it's probably <v1.0.4

**Closed by face-hh** 2024-03-23 15:27 UTC
Labels: bug

**Comment by SleeplessScripter** [comment] 2024-03-23 16:00
> Closing as it's probably <v1.0.4
It is the version available at the time of issue opening,
It does say debug though, I don't know if that has anything to do with it.

**Comment by SleeplessScripter** [comment] 2024-03-23 16:00
![image](https://github.com/face-hh/griddycode/assets/104847775/6044f277-cc6e-4761-ab17-3c71d69ec719)

**Comment by face-hh** [comment] 2024-03-23 16:02
Could you share a picture of your settings? The version should be there
