### ISSUE TITLE
Came here from the video, can't seem to start it

### ISSUE THREAD

**Issue by daUnknownCoder** [face-hh/griddycode#96] opened 2024-03-29 11:09 UTC
**Describe the bug**

So i used godot engine to remake a `Bounce Tales` ![Bounce Tales](https://github.com/face-hh/griddycode/assets/84800625/018ffb19-9a38-4f9e-882b-bc1b2875186d) sort of thing a few months ago

so i have the godot app on my device, but i get some vulkan driver errors [Note: I havent installed and used Wine in ages if that is a problem...]...

**To Reproduce**
1. Just do `./Bussin\ GriddyCode.x86_64

**Expected behavior**
It to atleast start for now

**Log**
```bash
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
WARNING: XOpenIM failed
     at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5951)
ERROR: Required extension VK_KHR_surface not found, is a driver installed?
   at: _initialize_instance_extensions (drivers/vulkan/vulkan_context.cpp:468)
ERROR: Could not initialize Vulkan
   at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:6018)

(zenity:728673): Adwaita-WARNING **: 17:34:00.319: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:2394)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: BUG: Unreferenced static string to 0: TextServerDummy
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: IPUnix
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ResourceFormatImporterSaver
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: MovieWriterMJPEG
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: TextServerAdvanced
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ImageFormatLoader
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ResourceFormatSaver
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: MovieWriterPNGWAV
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ScriptLanguage
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ResourceFormatLoader
   at: unref (core/string/string_name.cpp:129)
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 6.9.5-arch1-1
 - WM: Hyprland (wayland)

**Comment by face-hh** [comment] 2024-03-29 13:00
Could you try X11 instead of Wayland?

**Comment by daUnknownCoder** [comment] 2024-03-29 14:12
No I don't use X11 anymore -------- Original message --------From: Face ***@***.***>Date: Fri, Mar 29, 2024, 16:00To: face-hh/griddycode ***@***.***>Cc: StellarCoder ***@***.***>, Author ***@***.***>Subject: Re: [face-hh/griddycode] Came here from the video, can't seem to start it (Issue #96)
Could you try X11 instead of Wayland?

**Comment by face-hh** [comment] 2024-03-29 16:18
Well, wayland is not supported for Godot 4.2 (it will in Godot 4.3). Duplicate of #24

**Closed** 2024-03-29 16:17 UTC
Labels: bug
