### ISSUE TITLE
how do i open a terminal?? 

### ISSUE THREAD

**Issue by SirPigari** [face-hh/griddycode#107] opened 2024-04-12 16:12 UTC
sorry im dumb

**Comment by RealPacket** [comment] 2024-04-14 11:56
- Press super key
- enter "Terminal"
- click on Terminal

**Comment by melloCoding** [comment] 2024-04-14 12:08
As far as I know GriddyCode does not have a built in terminal
#70 is working to add one I think

**Comment by face-hh** [comment] 2024-04-14 12:29
Duplicate of #70

**Closed by face-hh** 2024-04-14 12:29 UTC
